import type { Config } from "tailwindcss";
import forms from "@tailwindcss/forms";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/**/*.{ts,tsx}",
    "./tests/**/*.{ts,tsx}",
    "./stitch_official_assembly_community_portal/**/*.html",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#f9f9f9",
        "outline-variant": "#c4c6cf",
        "on-surface": "#1a1c1c",
        "primary-container": "#002147",
        "on-background": "#1a1c1c",
        "error-container": "#ffdad6",
        "tertiary-container": "#1c2228",
        "surface-container-highest": "#e2e2e2",
        "tertiary-fixed-dim": "#c1c7ce",
        "on-tertiary-fixed": "#161c22",
        "surface-container": "#eeeeee",
        "inverse-on-surface": "#f0f1f1",
        "secondary-container": "#659dfe",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#003370",
        "surface-variant": "#e2e2e2",
        "primary-fixed": "#d6e3ff",
        "inverse-primary": "#aec7f6",
        "surface-tint": "#465f88",
        "surface-dim": "#dadada",
        error: "#ba1a1a",
        "primary-fixed-dim": "#aec7f6",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#001b3d",
        "on-error": "#ffffff",
        "on-primary-container": "#708ab5",
        "inverse-surface": "#2f3131",
        primary: "#000a1e",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#dde3eb",
        "on-secondary-fixed": "#001a40",
        tertiary: "#060b10",
        "surface-container-high": "#e8e8e8",
        "on-surface-variant": "#44474e",
        "on-primary-fixed-variant": "#2d476f",
        "secondary-fixed-dim": "#acc7ff",
        "surface-container-low": "#f3f3f4",
        "surface-bright": "#f9f9f9",
        "on-tertiary-container": "#838990",
        background: "#f9f9f9",
        outline: "#74777f",
        "on-secondary-fixed-variant": "#004491",
        "secondary-fixed": "#d7e2ff",
        "on-tertiary-fixed-variant": "#41474e",
        secondary: "#115cb9",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-mobile": "16px",
        "section-gap": "80px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "container-max": "1280px",
        "margin-desktop": "48px",
        "stack-sm": "8px",
        gutter: "24px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "title-lg": ["Inter", "sans-serif"],
        "headline-md": ["Playfair Display", "serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg": ["Playfair Display", "serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Playfair Display", "serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-sm": ["Playfair Display", "serif"],
      },
      fontSize: {
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "label-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": [
          "48px",
          { lineHeight: "60px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-lg-mobile": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "label-md": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" },
        ],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
      },
    },
  },
  plugins: [forms],
};

export default config;
